steps:
- task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@3
  displayName: 'Run CredScan'
  inputs:
    outputFormat: pre
    debugMode: false
  continueOnError: true