steps:
- task: securedevelopmentteam.vss-secure-development-tools.build-task-roslynanalyzers.RoslynAnalyzers@3
  displayName: 'Run Roslyn Analyzers'
  inputs:
    continueOnError: true
    # rulesetName: Custom
    msBuildVersion: 17.0
    msBuildArchitecture: amd64
    # customRuleset: $(Build.SourcesDirectory)\build\yaml\steps\codeanalysis\DevDivRoslynRequired.ruleset # create this file
    setupCommandLine: |
      # "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsMSBuildCmd.bat"
      "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsMSBuild.cmd"
    msBuildCommandline: |
      msbuild $(Build.SourcesDirectory)\src\MIDebugEngine.sln /p:Platform="Any CPU" /p:Configuration="Release"