steps:
- task: NuGetToolInstaller@0
  inputs:
    versionSpec: '5.8.0'

- task: NuGetCommand@2
  displayName: 'Restore MIEngine'
  inputs:
    restoreSolution: $(Build.SourcesDirectory)\src\MIDebugEngine.sln
    feedsToUse: config
    nugetConfigPath: $(Build.SourcesDirectory)\src\.nuget\NuGet.config

- task: securedevelopmentteam.vss-secure-development-tools.build-task-roslynanalyzers.RoslynAnalyzers@3
  displayName: 'Run Roslyn Analyzers'
  inputs:
    continueOnError: true
    # rulesetName: Custom
    msBuildVersion: 17.0
    msBuildArchitecture: amd64
    # customRuleset: $(Build.SourcesDirectory)\build\yaml\steps\codeanalysis\DevDivRoslynRequired.ruleset # create this file
    setupCommandLine: |
      "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsMSBuildCmd.bat"
    msBuildCommandline: |
      msbuild $(Build.SourcesDirectory)\src\MIDebugEngine.sln /p:Platform="Any CPU" /p:Configuration="Release"