steps:
- task: securedevelopmentteam.vss-secure-development-tools.build-task-roslynanalyzers.RoslynAnalyzers@3
  displayName: 'Run Roslyn Analyzers'
  inputs:
    continueOnError: true
    msBuildVersion: 17.0
    msBuildArchitecture: amd64
    setupCommandLine: |
      "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsMSBuildCmd.bat"
    msBuildCommandline: |
      msbuild $(Build.SourcesDirectory)\src\MIDebugEngine.sln /p:Platform="Any CPU" /p:Configuration="Release"