name: $(Date:yyyMMdd).$(Rev:r)
pr:
- 'main'
jobs:
- job: Debug
  pool:
    name: VSEng-MicroBuildVS2019
  steps:
  - task: NuGetToolInstaller@1
  - task: NuGetAuthenticate@0
    inputs:
      forceReinstallCredentialProvider: true
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      feedsToUse: 'config'
      nugetConfigPath: '$(Build.SourcesDirectory)\src\.nuget\NuGet.config'
  - task: MSBuild@1
    inputs:
      solution: '$(Build.SourcesDirectory)\src\MIDebugEngine.sln'
      configuration: 'Debug'
  - task: VSTest@2
    inputs:
      testAssemblyVer2: |
        $(Build.SourcesDirectory)\bin\Debug\MICoreUnitTests.dll
        $(Build.SourcesDirectory)\bin\Debug\JDbgUnitTests.dll
        $(Build.SourcesDirectory)\bin\Debug\SSHDebugTests.dll
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'xUnit'
      testResultsFiles: 'bin\Debug\TestResults.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)'
      testRunTitle: '$(Build.DefinitionName)_$(Build.BuildNumber)_Debug'

- job: Release
  pool:
    name: VSEng-MicroBuildVS2019
  steps:
  - task: NuGetToolInstaller@1
  - task: NuGetAuthenticate@0
    inputs:
      forceReinstallCredentialProvider: true
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      feedsToUse: 'config'
      nugetConfigPath: '$(Build.SourcesDirectory)\src\.nuget\NuGet.config'
  - task: MSBuild@1
    inputs:
      solution: '$(Build.SourcesDirectory)\src\MIDebugEngine.sln'
      configuration: 'Release'
  - task: VSTest@2
    inputs:
      testAssemblyVer2: |
        $(Build.SourcesDirectory)\bin\Release\MICoreUnitTests.dll
        $(Build.SourcesDirectory)\bin\Release\JDbgUnitTests.dll
        $(Build.SourcesDirectory)\bin\Release\SSHDebugTests.dll
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'xUnit'
      testResultsFiles: 'bin\Release\TestResults.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)'
      testRunTitle: '$(Build.DefinitionName)_$(Build.BuildNumber)_Release'

- job: DesktopDebug
  pool:
    name: VSEng-MicroBuildVS2019
  steps:
  - task: NuGetToolInstaller@1
  - task: NuGetAuthenticate@0
    inputs:
      forceReinstallCredentialProvider: true
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      feedsToUse: 'config'
      nugetConfigPath: '$(Build.SourcesDirectory)\src\.nuget\NuGet.config'
  - task: MSBuild@1
    inputs:
      solution: '$(Build.SourcesDirectory)\src\MIDebugEngine.sln'
      configuration: 'Desktop.Debug'

- job: DesktopRelease
  pool:
    name: VSEng-MicroBuildVS2019
  steps:
  - task: NuGetToolInstaller@1
  - task: NuGetAuthenticate@0
    inputs:
      forceReinstallCredentialProvider: true
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      feedsToUse: 'config'
      nugetConfigPath: '$(Build.SourcesDirectory)\src\.nuget\NuGet.config'
  - task: MSBuild@1
    inputs:
      solution: '$(Build.SourcesDirectory)\src\MIDebugEngine.sln'
      configuration: 'Desktop.Release'

- job: LabRelease
  pool:
    name: VSEng-MicroBuildVS2019
  variables:
    TEST_LAB_BUILD: 'true'
  steps:
  - task: NuGetToolInstaller@1
  - task: NuGetAuthenticate@0
    inputs:
      forceReinstallCredentialProvider: true
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      feedsToUse: 'config'
      nugetConfigPath: '$(Build.SourcesDirectory)\src\.nuget\NuGet.config'
  - task: MSBuild@1
    inputs:
      solution: '$(Build.SourcesDirectory)\src\MIDebugEngine.sln'
      configuration: 'Lab.Release'

- job: LabDebug
  pool:
    name: VSEng-MicroBuildVS2019
  variables:
    TEST_LAB_BUILD: 'true'
  steps:
  - task: NuGetToolInstaller@1
  - task: NuGetAuthenticate@0
    inputs:
      forceReinstallCredentialProvider: true
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      feedsToUse: 'config'
      nugetConfigPath: '$(Build.SourcesDirectory)\src\.nuget\NuGet.config'
  - task: MSBuild@1
    inputs:
      solution: '$(Build.SourcesDirectory)\src\MIDebugEngine.sln'
      configuration: 'Lab.Debug'