name: $(Date:yyyMMdd).$(Rev:r)
pr:
- 'main'
stages:
- stage: Windows
  dependsOn: []
  jobs:
  - job: Debug
    pool: 'Hosted Windows 2019 with VS2019'
    steps:
    - task: NuGetToolInstaller@1
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        feedsToUse: 'config'
        nugetConfigPath: '$(Build.SourcesDirectory)\src\.nuget\NuGet.config'
    - task: MSBuild@1
      inputs:
        solution: '$(Build.SourcesDirectory)\src\MIDebugEngine.sln'
        configuration: 'Debug'
    - task: VSTest@2
      inputs:
        testAssemblyVer2: |
          $(Build.SourcesDirectory)\bin\Debug\tests\MICoreUnitTests.dll
          $(Build.SourcesDirectory)\bin\Debug\tests\JDbgUnitTests.dll
          $(Build.SourcesDirectory)\bin\Debug\tests\SSHDebugTests.dll
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'xUnit'
        testResultsFiles: 'bin\Debug\TestResults.xml'
        searchFolder: '$(System.DefaultWorkingDirectory)'
        testRunTitle: '$(Build.DefinitionName)_$(Build.BuildNumber)_Debug'

  - job: Release
    pool: 'Hosted Windows 2019 with VS2019'
    steps:
    - task: NuGetToolInstaller@1
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        feedsToUse: 'config'
        nugetConfigPath: '$(Build.SourcesDirectory)\src\.nuget\NuGet.config'
    - task: MSBuild@1
      inputs:
        solution: '$(Build.SourcesDirectory)\src\MIDebugEngine.sln'
        configuration: 'Release'
    - task: VSTest@2
      inputs:
        testAssemblyVer2: |
          $(Build.SourcesDirectory)\bin\Release\tests\MICoreUnitTests.dll
          $(Build.SourcesDirectory)\bin\Release\tests\JDbgUnitTests.dll
          $(Build.SourcesDirectory)\bin\Release\tests\SSHDebugTests.dll
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'xUnit'
        testResultsFiles: 'bin\Release\TestResults.xml'
        searchFolder: '$(System.DefaultWorkingDirectory)'
        testRunTitle: '$(Build.DefinitionName)_$(Build.BuildNumber)_Release'

  - job: LabRelease
    pool: 'Hosted Windows 2019 with VS2019'
    variables:
      TEST_LAB_BUILD: 'true'
    steps:
    - task: NuGetToolInstaller@1
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        feedsToUse: 'config'
        nugetConfigPath: '$(Build.SourcesDirectory)\src\.nuget\NuGet.config'
    - task: MSBuild@1
      inputs:
        solution: '$(Build.SourcesDirectory)\src\MIDebugEngine.sln'
        configuration: 'Lab.Release'

  - job: LabDebug
    pool: 'Hosted Windows 2019 with VS2019'
    variables:
      TEST_LAB_BUILD: 'true'
    steps:
    - task: NuGetToolInstaller@1
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        feedsToUse: 'config'
        nugetConfigPath: '$(Build.SourcesDirectory)\src\.nuget\NuGet.config'
    - task: MSBuild@1
      inputs:
        solution: '$(Build.SourcesDirectory)\src\MIDebugEngine.sln'
        configuration: 'Lab.Debug'

- stage: Linux
  dependsOn: []
  jobs:
  - job: Debug
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NuGetToolInstaller@1
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: sdk
        version: 5.x
    - task: DotNetCoreCLI@2
      inputs:
        projects: |
          $(Build.SourcesDirectory)/src/MIDebugEngine-Unix.sln
        arguments: '-c Debug'

  - job: Release
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NuGetToolInstaller@1
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: sdk
        version: 5.x
    - task: DotNetCoreCLI@2
      inputs:
        projects: |
          $(Build.SourcesDirectory)/src/MIDebugEngine-Unix.sln
        arguments: '-c Release'

- stage: OSX
  dependsOn: []
  jobs:
  - job: Debug
    pool:
      vmImage: 'macOS-latest'
    steps:
    - task: NuGetToolInstaller@1
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: sdk
        version: 5.x
    - task: DotNetCoreCLI@2
      inputs:
        projects: |
          $(Build.SourcesDirectory)/src/MIDebugEngine-Unix.sln
        arguments: '-c Debug'

  - job: Release
    pool:
      vmImage: 'macOS-latest'
    steps:
    - task: NuGetToolInstaller@1
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: sdk
        version: 5.x
    - task: DotNetCoreCLI@2
      inputs:
        projects: |
          $(Build.SourcesDirectory)/src/MIDebugEngine-Unix.sln
        arguments: '-c Release'