name: $(Date:yyyMMdd).$(Rev:r)
pr:
- 'main'
jobs:
- job: Debug
  pool: 'Hosted Windows 2019 with VS2019'
  steps:
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      feedsToUse: 'config'
      nugetConfigPath: '$(Build.SourcesDirectory)\src\.nuget\NuGet.config'
  - task: MSBuild@1
    inputs:
      solution: '$(Build.SourcesDirectory)\src\MIDebugEngine.sln'
      configuration: 'Debug'
  - task: VSTest@2
    inputs:
      testAssemblyVer2: |
        $(Build.SourcesDirectory)\bin\Debug\MICoreUnitTests.dll
        $(Build.SourcesDirectory)\bin\Debug\JDbgUnitTests.dll
        $(Build.SourcesDirectory)\bin\Debug\SSHDebugTests.dll
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'xUnit'
      testResultsFiles: 'bin\Debug\TestResults.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)'
      testRunTitle: '$(Build.DefinitionName)_$(Build.BuildNumber)_Debug'

- job: Release
  pool: 'Hosted Windows 2019 with VS2019'
  steps:
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      feedsToUse: 'config'
      nugetConfigPath: '$(Build.SourcesDirectory)\src\.nuget\NuGet.config'
  - task: MSBuild@1
    inputs:
      solution: '$(Build.SourcesDirectory)\src\MIDebugEngine.sln'
      configuration: 'Release'
  - task: VSTest@2
    inputs:
      testAssemblyVer2: |
        $(Build.SourcesDirectory)\bin\Release\MICoreUnitTests.dll
        $(Build.SourcesDirectory)\bin\Release\JDbgUnitTests.dll
        $(Build.SourcesDirectory)\bin\Release\SSHDebugTests.dll
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'xUnit'
      testResultsFiles: 'bin\Release\TestResults.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)'
      testRunTitle: '$(Build.DefinitionName)_$(Build.BuildNumber)_Release'

- job: DesktopDebug
  pool: 'Hosted Windows 2019 with VS2019'
  steps:
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      feedsToUse: 'config'
      nugetConfigPath: '$(Build.SourcesDirectory)\src\.nuget\NuGet.config'
  - task: MSBuild@1
    inputs:
      solution: '$(Build.SourcesDirectory)\src\MIDebugEngine.sln'
      configuration: 'Desktop.Debug'

- job: DesktopRelease
  pool: 'Hosted Windows 2019 with VS2019'
  steps:
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      feedsToUse: 'config'
      nugetConfigPath: '$(Build.SourcesDirectory)\src\.nuget\NuGet.config'
  - task: MSBuild@1
    inputs:
      solution: '$(Build.SourcesDirectory)\src\MIDebugEngine.sln'
      configuration: 'Desktop.Release'

- job: LinuxDesktopDebug
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    inputs:
      packageType: sdk
      version: 5.x
  - task: DotNetCoreCLI@2
    inputs:
      projects: |
        $(Build.SourcesDirectory)/src/MIDebugEngine.sln
      arguments: '-c Desktop.Debug'

- job: LinuxDesktopRelease
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    inputs:
      packageType: sdk
      version: 5.x
  - task: DotNetCoreCLI@2
    inputs:
      projects: |
        $(Build.SourcesDirectory)/src/MIDebugEngine.sln
      arguments: '-c Desktop.Release'

- job: LabRelease
  pool: 'Hosted Windows 2019 with VS2019'
  variables:
    TEST_LAB_BUILD: 'true'
  steps:
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      feedsToUse: 'config'
      nugetConfigPath: '$(Build.SourcesDirectory)\src\.nuget\NuGet.config'
  - task: MSBuild@1
    inputs:
      solution: '$(Build.SourcesDirectory)\src\MIDebugEngine.sln'
      configuration: 'Lab.Release'

- job: LabDebug
  pool: 'Hosted Windows 2019 with VS2019'
  variables:
    TEST_LAB_BUILD: 'true'
  steps:
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      feedsToUse: 'config'
      nugetConfigPath: '$(Build.SourcesDirectory)\src\.nuget\NuGet.config'
  - task: MSBuild@1
    inputs:
      solution: '$(Build.SourcesDirectory)\src\MIDebugEngine.sln'
      configuration: 'Lab.Debug'