//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SSHDebugPS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.SSHDebugPS.UI.UIResources", typeof(UIResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New SSH Connection.
        /// </summary>
        public static string AddNewSSHConnectionAutomationName {
            get {
                return ResourceManager.GetString("AddNewSSHConnectionAutomationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add....
        /// </summary>
        public static string AddNewSSHConnectionLabel {
            get {
                return ResourceManager.GetString("AddNewSSHConnectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new SSH connection to a remote machine..
        /// </summary>
        public static string AddNewSSHConnectionToolTip {
            get {
                return ResourceManager.GetString("AddNewSSHConnectionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Advanced Settings.
        /// </summary>
        public static string AdvancedSettingsHeader {
            get {
                return ResourceManager.GetString("AdvancedSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_ancel.
        /// </summary>
        public static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapsed.
        /// </summary>
        public static string Collapsed {
            get {
                return ResourceManager.GetString("Collapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing command &apos;{0}&apos; failed. {1}.
        /// </summary>
        public static string CommandExecutionErrorFormat {
            get {
                return ResourceManager.GetString("CommandExecutionErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing command &apos;{0}&apos; failed with exit code &apos;{1}&apos;. &apos;{2}&apos;.
        /// </summary>
        public static string CommandExecutionErrorWithExitCodeFormat {
            get {
                return ResourceManager.GetString("CommandExecutionErrorWithExitCodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command: .
        /// </summary>
        public static string CommandLabelText {
            get {
                return ResourceManager.GetString("CommandLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docker _CLI host:.
        /// </summary>
        public static string ConnectionLabel {
            get {
                return ResourceManager.GetString("ConnectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location from which to run the Docker CLI. To manage remote connections, in the menu go to Tools -&gt; Options and find Cross Platform -&gt; Connection Manager..
        /// </summary>
        public static string ConnectionToolTip {
            get {
                return ResourceManager.GetString("ConnectionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container List.
        /// </summary>
        public static string ContainerList {
            get {
                return ResourceManager.GetString("ContainerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} containers..
        /// </summary>
        public static string ContainersFoundStatusText {
            get {
                return ResourceManager.GetString("ContainersFoundStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container Status:.
        /// </summary>
        public static string ContainerStatusTextBox {
            get {
                return ResourceManager.GetString("ContainerStatusTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created: .
        /// </summary>
        public static string CreatedLabelText {
            get {
                return ResourceManager.GetString("CreatedLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Docker Container.
        /// </summary>
        public static string DialogTitle {
            get {
                return ResourceManager.GetString("DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string ErrorStatusTextFormat {
            get {
                return ResourceManager.GetString("ErrorStatusTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/hide container details.
        /// </summary>
        public static string ExpandCommandAutomationName {
            get {
                return ResourceManager.GetString("ExpandCommandAutomationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanded.
        /// </summary>
        public static string Expanded {
            get {
                return ResourceManager.GetString("Expanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Container Details.
        /// </summary>
        public static string ExpanderToolTip {
            get {
                return ResourceManager.GetString("ExpanderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Docker Host name.
        /// </summary>
        public static string HostnameAutomationName {
            get {
                return ResourceManager.GetString("HostnameAutomationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docker _host (Optional):.
        /// </summary>
        public static string HostnameLabel {
            get {
                return ResourceManager.GetString("HostnameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a hostname for connecting to a different Docker host. .
        /// </summary>
        public static string HostnameTip {
            get {
                return ResourceManager.GetString("HostnameTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id: .
        /// </summary>
        public static string IdLabelText {
            get {
                return ResourceManager.GetString("IdLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image: .
        /// </summary>
        public static string ImageLabelText {
            get {
                return ResourceManager.GetString("ImageLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Connection.
        /// </summary>
        public static string IsLocalConnectionLabel {
            get {
                return ResourceManager.GetString("IsLocalConnectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Machine.
        /// </summary>
        public static string LocalMachine {
            get {
                return ResourceManager.GetString("LocalMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        public static string NameLabelText {
            get {
                return ResourceManager.GetString("NameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Containers Found..
        /// </summary>
        public static string NoContainersFound {
            get {
                return ResourceManager.GetString("NoContainersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string NoPortsText {
            get {
                return ResourceManager.GetString("NoPortsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _OK.
        /// </summary>
        public static string OKLabel {
            get {
                return ResourceManager.GetString("OKLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string OptionalHintText {
            get {
                return ResourceManager.GetString("OptionalHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ports: .
        /// </summary>
        public static string PortsLabelText {
            get {
                return ResourceManager.GetString("PortsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Querying Docker command....
        /// </summary>
        public static string QueryingDockerCommandMessage {
            get {
                return ResourceManager.GetString("QueryingDockerCommandMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Querying for containers....
        /// </summary>
        public static string QueryingForContainersMessage {
            get {
                return ResourceManager.GetString("QueryingForContainersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshHyperlink {
            get {
                return ResourceManager.GetString("RefreshHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Container List.
        /// </summary>
        public static string RefreshToolTip {
            get {
                return ResourceManager.GetString("RefreshToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Connection.
        /// </summary>
        public static string RemoteConnectionStringLabel {
            get {
                return ResourceManager.GetString("RemoteConnectionStringLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        public static string SearchingStatusText {
            get {
                return ResourceManager.GetString("SearchingStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting via SSH....
        /// </summary>
        public static string SSHConnectingStatusText {
            get {
                return ResourceManager.GetString("SSHConnectingStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSH Connection failed. Press Refresh to try again..
        /// </summary>
        public static string SSHConnectionFailedStatusText {
            get {
                return ResourceManager.GetString("SSHConnectionFailedStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: .
        /// </summary>
        public static string StatusLabelText {
            get {
                return ResourceManager.GetString("StatusLabelText", resourceCulture);
            }
        }
    }
}
