---
name: $(Date:yyyMMdd).$(Rev:r)
variables:
- name: SignType
  value: test
- name: TeamName
  value: MDDDebugger
jobs:
- template: ./jobs/VSEngSS-MicroBuild2019-1ES.job.yml
  parameters:
    DisplayName: DebuggerTesting
    JobTemplate:
    - template: ../templates/DebuggerTesting-release.template.yml
...