---
name: $(Date:yyyMMdd).$(Rev:r)
variables:
  - group: TSDTUSR
jobs:
- template: ./jobs/VSEngSS-MicroBuild2019-1ES.job.yml
  parameters:
    DisplayName: 'VS_Release'
    JobTemplate:
    - template: ../templates/VS-release.template.yml

...