---
name: $(Date:yyyMMdd).$(Rev:r)

trigger: none

variables:
- name: TeamName
  value: MDDDebugger

resources:
  repositories:
  - repository: MicroBuildTemplate
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate
    ref: refs/tags/release

extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  parameters:
    pool:
      name: VSEngSS-MicroBuild2022-1ES
      os: windows
    sdl:
      sourceAnalysisPool:
        name: VSEngSS-MicroBuild2022-1ES
        os: windows 
    stages:
    - stage: Windows
      jobs:
      - job: 
        displayName: Windows
        timeoutInMinutes: 180
        cancelTimeoutInMinutes: 1
        templateContext:
          mb:
            signing:
              enabled: true
              signType: real
              signWithProd: true
              zipSources: false
            localization:
              enabled: true
        steps:
        - template: /eng/pipelines/templates/VSCode-release.template.yml@self

    - stage: OSX_CodeSign
      dependsOn: [Windows]
      jobs:
      - template: /eng/pipelines/jobs/MSHosted-OSX.job.yml@self
        parameters:
          DisplayName: 'OSX Sign/Harden'
          JobTemplate:
          - template: ../templates/VSCode-codesign-osx.template.yml

    - stage: OSX_ESRPSign
      dependsOn: [OSX_CodeSign]
      jobs:
      - template: /eng/pipelines/jobs/VSEngSS-MicroBuild2022-1ES.job.yml@self
        parameters:
          DisplayName: 'OSX Sign/Harden'
          JobTemplate:
          - template: ../templates/VSCode-esrp-sign-osx.template.yml
...