// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Xml.Serialization;
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

namespace Microsoft.MIDebugEngine.Natvis
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/vstudio/debugger/natvis/2010")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/vstudio/debugger/natvis/2010", IsNullable = false)]
    public partial class AutoVisualizer
    {
        private VersionType _versionField;

        private LocalizedStringType[] _localizedStringsField;

        private UIVisualizerType[] _uIVisualizerField;

        private object[] _itemsField;

        /// <remarks/>
        public VersionType Version
        {
            get
            {
                return _versionField;
            }
            set
            {
                _versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("LocalizedString", IsNullable = false)]
        public LocalizedStringType[] LocalizedStrings
        {
            get
            {
                return _localizedStringsField;
            }
            set
            {
                _localizedStringsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UIVisualizer")]
        public UIVisualizerType[] UIVisualizer
        {
            get
            {
                return _uIVisualizerField;
            }
            set
            {
                _uIVisualizerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HResult", typeof(HResultType))]
        [System.Xml.Serialization.XmlElementAttribute("Type", typeof(VisualizerType))]
        [System.Xml.Serialization.XmlElementAttribute("Alias", typeof(AliasType))]
        public object[] Items
        {
            get
            {
                return _itemsField;
            }
            set
            {
                _itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/vstudio/debugger/natvis/2010")]
    public partial class VersionType
    {
        private string _nameField;

        private string _minField;

        private string _maxField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return _nameField;
            }
            set
            {
                _nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Min
        {
            get
            {
                return _minField;
            }
            set
            {
                _minField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Max
        {
            get
            {
                return _maxField;
            }
            set
            {
                _maxField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/vstudio/debugger/natvis/2010")]
    public partial class AlternativeHResultType
    {
        private string _nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return _nameField;
            }
            set
            {
                _nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/vstudio/debugger/natvis/2010")]
    public partial class HResultType
    {
        private AlternativeHResultType[] _alternativeHResultField;

        private string _hRValueField;

        private string _hRDescriptionField;

        private string _nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AlternativeHResult")]
        public AlternativeHResultType[] AlternativeHResult
        {
            get
            {
                return _alternativeHResultField;
            }
            set
            {
                _alternativeHResultField = value;
            }
        }

        /// <remarks/>
        public string HRValue
        {
            get
            {
                return _hRValueField;
            }
            set
            {
                _hRValueField = value;
            }
        }

        /// <remarks/>
        public string HRDescription
        {
            get
            {
                return _hRDescriptionField;
            }
            set
            {
                _hRDescriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return _nameField;
            }
            set
            {
                _nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/vstudio/debugger/natvis/2010")]
    public partial class UIVisualizerItemType
    {
        private string _serviceIdField;

        private int _idField;

        private string _valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ServiceId
        {
            get
            {
                return _serviceIdField;
            }
            set
            {
                _serviceIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Id
        {
            get
            {
                return _idField;
            }
            set
            {
                _idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return _valueField;
            }
            set
            {
                _valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "ExpandType", Namespace = "http://schemas.microsoft.com/vstudio/debugger/natvis/2010")]
    public partial class ExpandType1
    {
        private object[] _itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ArrayItems", typeof(ArrayItemsType))]
        [System.Xml.Serialization.XmlElementAttribute("CustomListItems", typeof(CustomListItemsType))]
        [System.Xml.Serialization.XmlElementAttribute("ExpandedItem", typeof(ExpandedItemType))]
        [System.Xml.Serialization.XmlElementAttribute("IndexListItems", typeof(IndexListItemsType))]
        [System.Xml.Serialization.XmlElementAttribute("Item", typeof(ItemType))]
        [System.Xml.Serialization.XmlElementAttribute("LinkedListItems", typeof(LinkedListItemsType))]
        [System.Xml.Serialization.XmlElementAttribute("Synthetic", typeof(SyntheticItemType))]
        [System.Xml.Serialization.XmlElementAttribute("TreeItems", typeof(TreeItemsType))]
        public object[] Items
        {
            get
            {
                return _itemsField;
            }
            set
            {
                _itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/vstudio/debugger/natvis/2010")]
    public partial class ArrayItemsType
    {
        private ArrayDirectionType _directionField;

        private bool _directionFieldSpecified;

        private string _rankField;

        private string _sizeField;

        private string _lowerBoundField;

        private ValuePointerType[] _valuePointerField;

        private bool _optionalField;

        private bool _optionalFieldSpecified;

        private string _conditionField;

        /// <remarks/>
        public ArrayDirectionType Direction
        {
            get
            {
                return _directionField;
            }
            set
            {
                _directionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DirectionSpecified
        {
            get
            {
                return _directionFieldSpecified;
            }
            set
            {
                _directionFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string Rank
        {
            get
            {
                return _rankField;
            }
            set
            {
                _rankField = value;
            }
        }

        /// <remarks/>
        public string Size
        {
            get
            {
                return _sizeField;
            }
            set
            {
                _sizeField = value;
            }
        }

        /// <remarks/>
        public string LowerBound
        {
            get
            {
                return _lowerBoundField;
            }
            set
            {
                _lowerBoundField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ValuePointer")]
        public ValuePointerType[] ValuePointer
        {
            get
            {
                return _valuePointerField;
            }
            set
            {
                _valuePointerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Optional
        {
            get
            {
                return _optionalField;
            }
            set
            {
                _optionalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OptionalSpecified
        {
            get
            {
                return _optionalFieldSpecified;
            }
            set
            {
                _optionalFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition
        {
            get
            {
                return _conditionField;
            }
            set
            {
                _conditionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/vstudio/debugger/natvis/2010")]
    public enum ArrayDirectionType
    {
        /// <remarks/>
        Forward,

        /// <remarks/>
        Backward,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/vstudio/debugger/natvis/2010")]
    public partial class ValuePointerType
    {
        private string _conditionField;

        private string _valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition
        {
            get
            {
                return _conditionField;
            }
            set
            {
                _conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return _valueField;
            }
            set
            {
                _valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/vstudio/debugger/natvis/2010")]
    public partial class CustomListItemsType
    {
        private VariableType[] _itemsField;

        private CustomListSizeType[] _items1Field;

        private SkipType _itemField;

        private bool _optionalField;

        private bool _optionalFieldSpecified;

        private string _conditionField;

        private uint _maxItemsPerViewField;

        private bool _maxItemsPerViewFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Variable")]
        public VariableType[] Items
        {
            get
            {
                return _itemsField;
            }
            set
            {
                _itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Size")]
        public CustomListSizeType[] Items1
        {
            get
            {
                return _items1Field;
            }
            set
            {
                _items1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Skip")]
        public SkipType Item
        {
            get
            {
                return _itemField;
            }
            set
            {
                _itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Optional
        {
            get
            {
                return _optionalField;
            }
            set
            {
                _optionalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OptionalSpecified
        {
            get
            {
                return _optionalFieldSpecified;
            }
            set
            {
                _optionalFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition
        {
            get
            {
                return _conditionField;
            }
            set
            {
                _conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint MaxItemsPerView
        {
            get
            {
                return _maxItemsPerViewField;
            }
            set
            {
                _maxItemsPerViewField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxItemsPerViewSpecified
        {
            get
            {
                return _maxItemsPerViewFieldSpecified;
            }
            set
            {
                _maxItemsPerViewFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/vstudio/debugger/natvis/2010")]
    public partial class VariableType
    {
        private string _nameField;

        private string _initialValueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return _nameField;
            }
            set
            {
                _nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InitialValue
        {
            get
            {
                return _initialValueField;
            }
            set
            {
                _initialValueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/vstudio/debugger/natvis/2010")]
    public partial class CustomListSizeType
    {
        private string _conditionField;

        private string _valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition
        {
            get
            {
                return _conditionField;
            }
            set
            {
                _conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return _valueField;
            }
            set
            {
                _valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/vstudio/debugger/natvis/2010")]
    public partial class SkipType
    {
        private string _valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value
        {
            get
            {
                return _valueField;
            }
            set
            {
                _valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/vstudio/debugger/natvis/2010")]
    public partial class ExpandedItemType
    {
        private bool _optionalField;

        private bool _optionalFieldSpecified;

        private string _conditionField;

        private string _valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Optional
        {
            get
            {
                return _optionalField;
            }
            set
            {
                _optionalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OptionalSpecified
        {
            get
            {
                return _optionalFieldSpecified;
            }
            set
            {
                _optionalFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition
        {
            get
            {
                return _conditionField;
            }
            set
            {
                _conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return _valueField;
            }
            set
            {
                _valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/vstudio/debugger/natvis/2010")]
    public partial class IndexListItemsType
    {
        private IndexNodeType[] _sizeField;

        private IndexNodeType[] _valueNodeField;

        private bool _optionalField;

        private bool _optionalFieldSpecified;

        private string _conditionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Size")]
        public IndexNodeType[] Size
        {
            get
            {
                return _sizeField;
            }
            set
            {
                _sizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ValueNode")]
        public IndexNodeType[] ValueNode
        {
            get
            {
                return _valueNodeField;
            }
            set
            {
                _valueNodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Optional
        {
            get
            {
                return _optionalField;
            }
            set
            {
                _optionalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OptionalSpecified
        {
            get
            {
                return _optionalFieldSpecified;
            }
            set
            {
                _optionalFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition
        {
            get
            {
                return _conditionField;
            }
            set
            {
                _conditionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/vstudio/debugger/natvis/2010")]
    public partial class IndexNodeType
    {
        private string _conditionField;

        private string _valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition
        {
            get
            {
                return _conditionField;
            }
            set
            {
                _conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return _valueField;
            }
            set
            {
                _valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/vstudio/debugger/natvis/2010")]
    public partial class ItemType
    {
        private string _nameField;

        private bool _optionalField;

        private bool _optionalFieldSpecified;

        private string _conditionField;

        private string _valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return _nameField;
            }
            set
            {
                _nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Optional
        {
            get
            {
                return _optionalField;
            }
            set
            {
                _optionalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OptionalSpecified
        {
            get
            {
                return _optionalFieldSpecified;
            }
            set
            {
                _optionalFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition
        {
            get
            {
                return _conditionField;
            }
            set
            {
                _conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return _valueField;
            }
            set
            {
                _valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/vstudio/debugger/natvis/2010")]
    public partial class LinkedListItemsType
    {
        private string _sizeField;

        private string _headPointerField;

        private string _nextPointerField;

        private string _valueNodeField;

        private bool _optionalField;

        private bool _optionalFieldSpecified;

        private string _conditionField;

        private bool _noValueHeadPointer;

        /// <remarks/>
        public string Size
        {
            get
            {
                return _sizeField;
            }
            set
            {
                _sizeField = value;
            }
        }

        /// <remarks/>
        public string HeadPointer
        {
            get
            {
                return _headPointerField;
            }
            set
            {
                _headPointerField = value;
            }
        }

        /// <remarks/>
        public string NextPointer
        {
            get
            {
                return _nextPointerField;
            }
            set
            {
                _nextPointerField = value;
            }
        }

        /// <remarks/>
        public string ValueNode
        {
            get
            {
                return _valueNodeField;
            }
            set
            {
                _valueNodeField = value;
            }
        }

        public bool NoValueHeadPointer
        {
            get
            {
                return _noValueHeadPointer;
            }
            set
            {
                _noValueHeadPointer = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Optional
        {
            get
            {
                return _optionalField;
            }
            set
            {
                _optionalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OptionalSpecified
        {
            get
            {
                return _optionalFieldSpecified;
            }
            set
            {
                _optionalFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition
        {
            get
            {
                return _conditionField;
            }
            set
            {
                _conditionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/vstudio/debugger/natvis/2010")]
    public partial class SyntheticItemType
    {
        private CustomVisualizerType[] _customVisualizerField;

        private DisplayStringType[] _displayStringField;

        private StringViewType[] _stringViewField;

        private object[] _expandField;

        private string _nameField;

        private string _expressionField;

        private bool _optionalField;

        private bool _optionalFieldSpecified;

        private string _conditionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CustomVisualizer")]
        public CustomVisualizerType[] CustomVisualizer
        {
            get
            {
                return _customVisualizerField;
            }
            set
            {
                _customVisualizerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DisplayString")]
        public DisplayStringType[] DisplayString
        {
            get
            {
                return _displayStringField;
            }
            set
            {
                _displayStringField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StringView")]
        public StringViewType[] StringView
        {
            get
            {
                return _stringViewField;
            }
            set
            {
                _stringViewField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayItems", typeof(ArrayItemsType), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("CustomListItems", typeof(CustomListItemsType), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ExpandedItem", typeof(ExpandedItemType), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("IndexListItems", typeof(IndexListItemsType), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", typeof(ItemType), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("LinkedListItems", typeof(LinkedListItemsType), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Synthetic", typeof(SyntheticItemType), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("TreeItems", typeof(TreeItemsType), IsNullable = false)]
        public object[] Expand
        {
            get
            {
                return _expandField;
            }
            set
            {
                _expandField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return _nameField;
            }
            set
            {
                _nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Expression
        {
            get
            {
                return _expressionField;
            }
            set
            {
                _expressionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Optional
        {
            get
            {
                return _optionalField;
            }
            set
            {
                _optionalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OptionalSpecified
        {
            get
            {
                return _optionalFieldSpecified;
            }
            set
            {
                _optionalFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition
        {
            get
            {
                return _conditionField;
            }
            set
            {
                _conditionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/vstudio/debugger/natvis/2010")]
    public partial class CustomVisualizerType
    {
        private string _visualizerIdField;

        private bool _optionalField;

        private bool _optionalFieldSpecified;

        private string _conditionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VisualizerId
        {
            get
            {
                return _visualizerIdField;
            }
            set
            {
                _visualizerIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Optional
        {
            get
            {
                return _optionalField;
            }
            set
            {
                _optionalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OptionalSpecified
        {
            get
            {
                return _optionalFieldSpecified;
            }
            set
            {
                _optionalFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition
        {
            get
            {
                return _conditionField;
            }
            set
            {
                _conditionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/vstudio/debugger/natvis/2010")]
    public partial class DisplayStringType
    {
        private bool _optionalField;

        private bool _optionalFieldSpecified;

        private string _conditionField;

        private string _legacyAddinField;

        private string _exportField;

        private string _valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Optional
        {
            get
            {
                return _optionalField;
            }
            set
            {
                _optionalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OptionalSpecified
        {
            get
            {
                return _optionalFieldSpecified;
            }
            set
            {
                _optionalFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition
        {
            get
            {
                return _conditionField;
            }
            set
            {
                _conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LegacyAddin
        {
            get
            {
                return _legacyAddinField;
            }
            set
            {
                _legacyAddinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Export
        {
            get
            {
                return _exportField;
            }
            set
            {
                _exportField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return _valueField;
            }
            set
            {
                _valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/vstudio/debugger/natvis/2010")]
    public partial class StringViewType
    {
        private bool _optionalField;

        private bool _optionalFieldSpecified;

        private string _conditionField;

        private string _valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Optional
        {
            get
            {
                return _optionalField;
            }
            set
            {
                _optionalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OptionalSpecified
        {
            get
            {
                return _optionalFieldSpecified;
            }
            set
            {
                _optionalFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition
        {
            get
            {
                return _conditionField;
            }
            set
            {
                _conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return _valueField;
            }
            set
            {
                _valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/vstudio/debugger/natvis/2010")]
    public partial class TreeItemsType
    {
        private string _sizeField;

        private string _headPointerField;

        private string _leftPointerField;

        private string _rightPointerField;

        private IndexNodeType _valueNodeField;

        private bool _optionalField;

        private bool _optionalFieldSpecified;

        private string _conditionField;

        /// <remarks/>
        public string Size
        {
            get
            {
                return _sizeField;
            }
            set
            {
                _sizeField = value;
            }
        }

        /// <remarks/>
        public string HeadPointer
        {
            get
            {
                return _headPointerField;
            }
            set
            {
                _headPointerField = value;
            }
        }

        /// <remarks/>
        public string LeftPointer
        {
            get
            {
                return _leftPointerField;
            }
            set
            {
                _leftPointerField = value;
            }
        }

        /// <remarks/>
        public string RightPointer
        {
            get
            {
                return _rightPointerField;
            }
            set
            {
                _rightPointerField = value;
            }
        }

        /// <remarks/>
        public IndexNodeType ValueNode
        {
            get
            {
                return _valueNodeField;
            }
            set
            {
                _valueNodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Optional
        {
            get
            {
                return _optionalField;
            }
            set
            {
                _optionalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OptionalSpecified
        {
            get
            {
                return _optionalFieldSpecified;
            }
            set
            {
                _optionalFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition
        {
            get
            {
                return _conditionField;
            }
            set
            {
                _conditionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/vstudio/debugger/natvis/2010")]
    public partial class AlternativeTypeType
    {
        private string _nameField;

        private int _priorityField;

        private bool _priorityFieldSpecified;

        private bool _inheritableField;

        private bool _inheritableFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return _nameField;
            }
            set
            {
                _nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Priority
        {
            get
            {
                return _priorityField;
            }
            set
            {
                _priorityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrioritySpecified
        {
            get
            {
                return _priorityFieldSpecified;
            }
            set
            {
                _priorityFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Inheritable
        {
            get
            {
                return _inheritableField;
            }
            set
            {
                _inheritableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InheritableSpecified
        {
            get
            {
                return _inheritableFieldSpecified;
            }
            set
            {
                _inheritableFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/vstudio/debugger/natvis/2010")]
    public partial class VisualizerType
    {
        private AlternativeTypeType[] _alternativeTypeField;

        private VersionType _versionField;

        private CustomVisualizerType[] _customVisualizerField;

        private object[] _itemsField;

        private string _nameField;

        private string _includeViewField;

        private string _excludeViewField;

        private int _priorityField;

        private bool _priorityFieldSpecified;

        private bool _inheritableField;

        private bool _inheritableFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AlternativeType")]
        public AlternativeTypeType[] AlternativeType
        {
            get
            {
                return _alternativeTypeField;
            }
            set
            {
                _alternativeTypeField = value;
            }
        }

        /// <remarks/>
        public VersionType Version
        {
            get
            {
                return _versionField;
            }
            set
            {
                _versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CustomVisualizer")]
        public CustomVisualizerType[] CustomVisualizer
        {
            get
            {
                return _customVisualizerField;
            }
            set
            {
                _customVisualizerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DisplayString", typeof(DisplayStringType))]
        [System.Xml.Serialization.XmlElementAttribute("Expand", typeof(ExpandType1))]
        [System.Xml.Serialization.XmlElementAttribute("StringView", typeof(StringViewType))]
        [System.Xml.Serialization.XmlElementAttribute("UIVisualizer", typeof(UIVisualizerItemType))]
        public object[] Items
        {
            get
            {
                return _itemsField;
            }
            set
            {
                _itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return _nameField;
            }
            set
            {
                _nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IncludeView
        {
            get
            {
                return _includeViewField;
            }
            set
            {
                _includeViewField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ExcludeView
        {
            get
            {
                return _excludeViewField;
            }
            set
            {
                _excludeViewField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Priority
        {
            get
            {
                return _priorityField;
            }
            set
            {
                _priorityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrioritySpecified
        {
            get
            {
                return _priorityFieldSpecified;
            }
            set
            {
                _priorityFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Inheritable
        {
            get
            {
                return _inheritableField;
            }
            set
            {
                _inheritableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InheritableSpecified
        {
            get
            {
                return _inheritableFieldSpecified;
            }
            set
            {
                _inheritableFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/vstudio/debugger/natvis/2010")]
    public partial class UIVisualizerType
    {
        private string _serviceIdField;

        private int _idField;

        private string _menuNameField;

        private string _descriptionField;

        private string _valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ServiceId
        {
            get
            {
                return _serviceIdField;
            }
            set
            {
                _serviceIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Id
        {
            get
            {
                return _idField;
            }
            set
            {
                _idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MenuName
        {
            get
            {
                return _menuNameField;
            }
            set
            {
                _menuNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description
        {
            get
            {
                return _descriptionField;
            }
            set
            {
                _descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return _valueField;
            }
            set
            {
                _valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/vstudio/debugger/natvis/2010")]
    public partial class LocalizedStringType
    {
        private uint _idField;

        private string _valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Id
        {
            get
            {
                return _idField;
            }
            set
            {
                _idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return _valueField;
            }
            set
            {
                _valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/vstudio/debugger/natvis/2010")]
    public partial class AliasType
    {
        private string _valueField;

        private string _nameField;

        /// <remarks/>
        public string Value
        {
            get
            {
                return _valueField;
            }
            set
            {
                _valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return _nameField;
            }
            set
            {
                _nameField = value;
            }
        }
    }
}
